import "@/css/index.scss";
import styles from "@/css/sanguo.module.scss";

const list = [
  {
    lastName: "曹",
    firstName: "操",
    courtesyName: "孟德",
    camp: "WEI",
    command: 99,
    led: 91,
    valor: -7,
    force: -7,
    tactic: 84,
    strategy: 94,
  },
  {
    lastName: "程",
    firstName: "昱",
    courtesyName: "仲德",
    camp: "WEI",
    command: -5,
    led: -5,
    valor: -3,
    force: -3,
    tactic: 91,
    strategy: 87,
  },
  {
    lastName: "邓",
    firstName: "艾",
    courtesyName: "士载",
    camp: "WEI",
    command: 90,
    led: 92,
    valor: 83,
    force: 83,
    tactic: 87,
    strategy: 90,
  },
  {
    lastName: "典",
    firstName: "韦",
    courtesyName: "",
    camp: "WEI",
    command: -5,
    led: -5,
    valor: 99,
    force: 92,
    tactic: -3,
    strategy: -3,
  },
  {
    lastName: "法",
    firstName: "正",
    courtesyName: "孝直",
    camp: "SHU",
    command: -7,
    led: -7,
    valor: -4,
    force: -4,
    tactic: 91,
    strategy: 90,
  },
  {
    lastName: "甘",
    firstName: "宁",
    courtesyName: "兴霸",
    camp: "WU",
    command: 81,
    led: 84,
    valor: 92,
    force: 91,
    tactic: -5,
    strategy: -5,
  },
  {
    lastName: "高",
    firstName: "顺",
    courtesyName: "",
    camp: "QUN",
    command: 84,
    led: 88,
    valor: 86,
    force: 86,
    tactic: -6,
    strategy: -6,
  },
  {
    lastName: "关",
    firstName: "羽",
    courtesyName: "云长",
    camp: "SHU",
    command: 91,
    led: 94,
    valor: 94,
    force: 96,
    tactic: -7,
    strategy: -6,
  },
  {
    lastName: "郭",
    firstName: "嘉",
    courtesyName: "奉孝",
    camp: "WEI",
    command: -5,
    led: -5,
    valor: -3,
    force: -3,
    tactic: 95,
    strategy: 92,
  },
  {
    lastName: "黄",
    firstName: "盖",
    courtesyName: "公覆",
    camp: "WU",
    command: -7,
    led: 81,
    valor: 88,
    force: 86,
    tactic: -7,
    strategy: -7,
  },
  {
    lastName: "黄",
    firstName: "忠",
    courtesyName: "汉升",
    camp: "SHU",
    command: 80,
    led: 83,
    valor: 90,
    force: 92,
    tactic: -6,
    strategy: -6,
  },
  {
    lastName: "贾",
    firstName: "诩",
    courtesyName: "文和",
    camp: "WEI",
    command: -6,
    led: -6,
    valor: -3,
    force: -3,
    tactic: 99,
    strategy: 91,
  },
  {
    lastName: "姜",
    firstName: "维",
    courtesyName: "伯约",
    camp: "SHU",
    command: 92,
    led: 91,
    valor: 92,
    force: 91,
    tactic: 91,
    strategy: 91,
  },
  {
    lastName: "刘",
    firstName: "备",
    courtesyName: "玄德",
    camp: "SHU",
    command: 98,
    led: 87,
    valor: -7,
    force: -7,
    tactic: 82,
    strategy: 88,
  },
  {
    lastName: "鲁",
    firstName: "肃",
    courtesyName: "子敬",
    camp: "WU",
    command: 88,
    led: 82,
    valor: -5,
    force: -5,
    tactic: 89,
    strategy: 95,
  },
  {
    lastName: "陆",
    firstName: "逊",
    courtesyName: "伯言",
    camp: "WU",
    command: 92,
    led: 93,
    valor: -6,
    force: -6,
    tactic: 90,
    strategy: 86,
  },
  {
    lastName: "吕",
    firstName: "布",
    courtesyName: "奉先",
    camp: "QUN",
    command: 95,
    led: 82,
    valor: 95,
    force: 99,
    tactic: -4,
    strategy: -4,
  },
  {
    lastName: "吕",
    firstName: "蒙",
    courtesyName: "子明",
    camp: "WU",
    command: 90,
    led: 90,
    valor: 82,
    force: 84,
    tactic: 92,
    strategy: 85,
  },
  {
    lastName: "马",
    firstName: "超",
    courtesyName: "孟起",
    camp: "SHU",
    command: 83,
    led: 85,
    valor: 94,
    force: 95,
    tactic: -6,
    strategy: -6,
  },
  {
    lastName: "庞",
    firstName: "德",
    courtesyName: "令明",
    camp: "WEI",
    command: 80,
    led: 84,
    valor: 94,
    force: 91,
    tactic: -5,
    strategy: -5,
  },
  {
    lastName: "庞",
    firstName: "统",
    courtesyName: "士元",
    camp: "SHU",
    command: -7,
    led: 80,
    valor: -4,
    force: -4,
    tactic: 94,
    strategy: 94,
  },
  {
    lastName: "司马",
    firstName: "懿",
    courtesyName: "仲达",
    camp: "WEI",
    command: 92,
    led: 93,
    valor: -6,
    force: -6,
    tactic: 94,
    strategy: 94,
  },
  {
    lastName: "孙",
    firstName: "策",
    courtesyName: "伯符",
    camp: "WU",
    command: 97,
    led: 94,
    valor: 95,
    force: 94,
    tactic: -7,
    strategy: 87,
  },
  {
    lastName: "孙",
    firstName: "坚",
    courtesyName: "文台",
    camp: "WU",
    command: 95,
    led: 87,
    valor: 90,
    force: 91,
    tactic: -7,
    strategy: 83,
  },
  {
    lastName: "孙",
    firstName: "权",
    courtesyName: "仲谋",
    camp: "WU",
    command: 98,
    led: 82,
    valor: -7,
    force: -7,
    tactic: 83,
    strategy: 86,
  },
  {
    lastName: "太史",
    firstName: "慈",
    courtesyName: "子义",
    camp: "WU",
    command: 81,
    led: 84,
    valor: 93,
    force: 93,
    tactic: -6,
    strategy: -6,
  },
  {
    lastName: "魏",
    firstName: "延",
    courtesyName: "文长",
    camp: "SHU",
    command: 82,
    led: 86,
    valor: 90,
    force: 89,
    tactic: -6,
    strategy: -6,
  },
  {
    lastName: "夏侯",
    firstName: "惇",
    courtesyName: "元让",
    camp: "WEI",
    command: 85,
    led: 84,
    valor: 91,
    force: 89,
    tactic: -6,
    strategy: -6,
  },
  {
    lastName: "夏侯",
    firstName: "渊",
    courtesyName: "妙才",
    camp: "WEI",
    command: 80,
    led: 80,
    valor: 87,
    force: 87,
    tactic: -6,
    strategy: -6,
  },
  {
    lastName: "许",
    firstName: "褚",
    courtesyName: "仲康",
    camp: "WEI",
    command: -5,
    led: -5,
    valor: 98,
    force: 93,
    tactic: -3,
    strategy: -3,
  },
  {
    lastName: "徐",
    firstName: "晃",
    courtesyName: "公明",
    camp: "WEI",
    command: 80,
    led: 83,
    valor: 87,
    force: 87,
    tactic: -7,
    strategy: -7,
  },
  {
    lastName: "徐",
    firstName: "庶",
    courtesyName: "元直",
    camp: "SHU",
    command: -5,
    led: -5,
    valor: -4,
    force: -4,
    tactic: 92,
    strategy: 92,
  },
  {
    lastName: "荀",
    firstName: "攸",
    courtesyName: "公达",
    camp: "WEI",
    command: -5,
    led: -5,
    valor: -3,
    force: -3,
    tactic: 95,
    strategy: 93,
  },
  {
    lastName: "荀",
    firstName: "彧",
    courtesyName: "文若",
    camp: "WEI",
    command: -6,
    led: -5,
    valor: -3,
    force: -3,
    tactic: 91,
    strategy: 97,
  },
  {
    lastName: "于",
    firstName: "禁",
    courtesyName: "文则",
    camp: "WEI",
    command: 84,
    led: 88,
    valor: 82,
    force: 82,
    tactic: -7,
    strategy: -7,
  },
  {
    lastName: "乐",
    firstName: "进",
    courtesyName: "文谦",
    camp: "WEI",
    command: -7,
    led: -7,
    valor: 83,
    force: 83,
    tactic: -5,
    strategy: -5,
  },
  {
    lastName: "张",
    firstName: "郃",
    courtesyName: "俊乂",
    camp: "WEI",
    command: 80,
    led: 83,
    valor: 86,
    force: 86,
    tactic: -7,
    strategy: -7,
  },
  {
    lastName: "张",
    firstName: "飞",
    courtesyName: "翼德",
    camp: "SHU",
    command: 83,
    led: 87,
    valor: 97,
    force: 97,
    tactic: -6,
    strategy: -5,
  },
  {
    lastName: "张",
    firstName: "纮",
    courtesyName: "子纲",
    camp: "WU",
    command: -5,
    led: -4,
    valor: -3,
    force: -3,
    tactic: 89,
    strategy: 90,
  },
  {
    lastName: "张",
    firstName: "辽",
    courtesyName: "文远",
    camp: "WEI",
    command: 83,
    led: 86,
    valor: 92,
    force: 91,
    tactic: -7,
    strategy: -7,
  },
  {
    lastName: "张",
    firstName: "昭",
    courtesyName: "子布",
    camp: "WU",
    command: -5,
    led: -4,
    valor: -3,
    force: -3,
    tactic: 87,
    strategy: 92,
  },
  {
    lastName: "赵",
    firstName: "云",
    courtesyName: "子龙",
    camp: "SHU",
    command: 81,
    led: 83,
    valor: 95,
    force: 94,
    tactic: -7,
    strategy: -7,
  },
  {
    lastName: "周",
    firstName: "瑜",
    courtesyName: "公瑾",
    camp: "WU",
    command: 95,
    led: 99,
    valor: -7,
    force: -7,
    tactic: 90,
    strategy: 94,
  },
  {
    lastName: "诸葛",
    firstName: "亮",
    courtesyName: "孔明",
    camp: "SHU",
    command: 95,
    led: 98,
    valor: -3,
    force: -3,
    tactic: 98,
    strategy: 99,
  },
];

// 球形排列
const count = 12;
const xRotate = [0, 36, 72, 108, 144];
const yRotate = Array(count)
  .fill(1)
  .map((v, i) => (360 / count) * v * i);
const rotates: [number, number][] = [];
xRotate.forEach((x, i) => {
  yRotate.forEach((y, j) => {
    const cross = [3, 9];
    const side = [2, 4, 8, 10];
    if (
      !i ||
      (cross.indexOf(j) === -1 && (i % 2 === 0 || side.indexOf(j) === -1))
    ) {
      rotates.push([x, y]);
    }
  });
});

const div = document.createElement("div");
document.body.appendChild(div);

div.className = "wrap";
let content = '<div id="box" class="' + styles.box + '">';
for (let i = 0; i < list.length; i++) {
  content +=
    '<div class="' +
    styles.item +
    " " +
    styles[list[i].camp.toLowerCase()] +
    '" style="transform: rotateX(' +
    rotates[i][0] +
    "deg) rotateY(" +
    rotates[i][1] +
    'deg) translateZ(150px);"><span class="name">' +
    list[i].firstName +
    "</span></div>";
}
content += "<div>";
div.innerHTML = content;

const deg = { x: 0, y: 0 };
const step = { x: 1, y: 1 };
const box = <HTMLElement>document.querySelector("#box");
if (box) {
  window.setInterval(() => {
    deg.x += step.x;
    deg.y += step.y;
    box.style.transform = "rotateX(" + deg.x + "deg) rotateY(" + deg.y + "deg)";
  }, 30);
}
